### ISSUE TITLE
Question about data loading strategy

### ISSUE THREAD

**Issue by yangsizhe** [AlbertTan404/pytorch-open-x-embodiment#1]
Hi! Nice work!

I notice that the code loads all the data into memory. I'm wondering how much memory would be used if the entire open-x-embodiment dataset is loaded. Would it be more appropriate to save the data for each timestep separately in a file and load only a batch size of data into memory each time? Thanks in advance.

**Comment by AlbertTan404** [comment]
> Hi! Nice work!
> 
> I notice that the code loads all the data into memory. I'm wondering how much memory would be used if the entire open-x-embodiment dataset is loaded. Would it be more appropriate to save the data for each timestep separately in a file and load only a batch size of data into memory each time? Thanks in advance.

Great question! Loading all data into memory primarily enhances training efficiency. In our dataset template, we assume that all image data has been preprocessed with image encoders like CLIP or R3M. Since we don't train the image encoder in our workflow, the overall size remains affordable (n_images * 3 * image_size^2 * int8 -> n_images * 512 * fp32). In our practice, we filtered out some datasets and at last used 24 datasets, including bridge and rt1, resulting in a total size of approximately 100GB memory for each process.

**Comment by yangsizhe** [comment]
Understood. Thanks for your reply!
